name: Build LaTeX document
on:
  push:
    paths-ignore:
      - 'cwfs-report.pdf'
      - '**.md'
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Compile LateX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cwfs-report.tex
      - name: Upload PDF to repo
        run: |
          # Configure git to use name and email of whoever made the last commit
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          # Roll back git history to before last commit
          # This also adds all changes in the last commit to the working tree
          git reset --soft HEAD~1
          # Add pdf file to working tree
          git add cwfs-report.pdf
          # Commit changes and pdf using same commit info as before 
          git commit -C HEAD@{1}
          # Force push to overwrite git history
          git push --force
