name: Build LaTeX document
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Upload PDF to repo
        uses: EndBug/add-and-commit@v7.4.0
        with:
          add: 'main.pdf'
          pull: 'NO-PULL'
          push: origin +${branch input} --set-upstream

